services:
  monitoring-dashboard:
    build: .
    container_name: monitoring-dashboard
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4003:4003"
    restart: always
    env_file:
      - .env
